### ISSUE TITLE
Issue running example

### ISSUE THREAD

**Issue by Eillot29** [hongzimao/deeprm#18]
Hi,
I'm running the Example for the very first time.
I'm running the command presented there:

python launcher.py --exp_type=pg_re --pg_re=data/pg_su_net_file_20.pkl --simu_len=50 --num_ex=10 --ofile=data/pg_re

But I'm getting an error:
Traceback (most recent call last):
  File "launcher.py", line 163, in <module>
    main()
  File "launcher.py", line 149, in main
    pg_re.launch(pa, pg_resume, render, repre='image', end='all_done')
  File "/home/k8s-master/Desktop/Deeprm/deeprm-master/pg_re.py", line 315, in launch
    for r in manager_result:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 755, in _callmethod
    self._connect()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 742, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 169, in Client
    c = SocketClient(address)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 308, in SocketClient
    s.connect(address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused

Do you konw where I went wrong,and how to fix it?
Thanks.

**Comment by Eillot29** [comment]
pip list
asn1crypto (0.24.0)
attrs (19.3.0)
backports.functools-lru-cache (1.4)
backports.shutil-get-terminal-size (1.0.0)
backports.ssl-match-hostname (3.7.0.1)
bcrypt (3.1.7)
cached-property (1.5.1)
certifi (2020.4.5.1)
cffi (1.14.0)
chardet (3.0.4)
configparser (4.0.2)
contextlib2 (0.6.0.post1)
cryptography (2.9.2)
cycler (0.10.0)
decorator (4.1.2)
docker (4.2.0)
docker-compose (1.25.5)
dockerpty (0.4.1)
docopt (0.6.2)
enum34 (1.1.6)
functools32 (3.2.3.post2)
idna (2.6)
importlib-metadata (1.6.0)
iniparse (0.4)
ipaddress (1.0.17)
jsonschema (3.2.0)
keyring (10.6.0)
keyrings.alt (3.0)
Lasagne (0.1)
matplotlib (2.1.1)
nose (1.3.7)
numpy (1.13.3)
olefile (0.45.1)
paramiko (2.7.1)
pathlib2 (2.3.5)
Pillow (5.1.0)
pip (9.0.1)
pycparser (2.20)
pycrypto (2.6.1)
pycurl (7.43.0.1)
pygobject (3.26.1)
pyliblzma (0.5.3)
PyNaCl (1.3.0)
pyparsing (2.2.0)
pyrsistent (0.16.0)
pysqlite (1.0.1)
python-dateutil (2.6.1)
pytz (2018.3)
pyxdg (0.25)
PyYAML (5.3.1)
requests (2.23.0)
rpm (4.14.1)
scandir (1.10.0)
scipy (0.19.1)
SecretStorage (2.3.1)
setuptools (39.0.1)
six (1.11.0)
subprocess32 (3.5.4)
texttable (1.6.2)
Theano (1.0.5)
urlgrabber (3.10.2)
urllib3 (1.25.9)
websocket-client (0.57.0)
wheel (0.30.0)
yum-metadata-parser (1.1.4)
zipp (1.2.0)
