### ISSUE TITLE
Issue running examples

### ISSUE THREAD

**Issue by ArikRinberg** [hongzimao/deeprm#5]
Hi,
 
I'm trying to rerun your experiments in order to recreate the graphs. However, I'm getting errors when running the github.
 
I'm running the command presented there:
 python launcher.py --exp_type=pg_re --pg_re=data/pg_su_net_file_20.pkl --simu_len=50 --num_ex=10 --ofile=data/pg_re
 
But I'm getting an error:
Traceback (most recent call last):
  File "launcher.py", line 10, in <module>
    import pg_su
  File "/home/arik/deeprm/pg_su.py", line 12, in <module>
    np.set_printoptions(threshold='nan')
  File "/home/arik/.local/lib/python2.7/site-packages/numpy/core/arrayprint.py", line 246, in set_printoptions
    floatmode, legacy)
  File "/home/arik/.local/lib/python2.7/site-packages/numpy/core/arrayprint.py", line 93, in _make_options_dict
    raise ValueError("threshold must be numeric and non-NAN, try "
ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation
 
The versions:
>pip list
asn1crypto (0.24.0)
backports.functools-lru-cache (1.4)
cryptography (2.1.4)
cycler (0.10.0)
decorator (4.1.2)
enum34 (1.1.6)
idna (2.6)
ipaddress (1.0.17)
keyring (10.6.0)
keyrings.alt (3.0)
Lasagne (0.2.dev1)
matplotlib (2.1.1)
nose (1.3.7)
numpy (1.16.2)
olefile (0.45.1)
Pillow (5.1.0)
pip (9.0.1)
pycrypto (2.6.1)
pygobject (3.26.1)
pyparsing (2.2.0)
python-dateutil (2.6.1)
pytz (2018.3)
pyxdg (0.25)
scipy (1.2.1)
SecretStorage (2.3.1)
setuptools (39.0.1)
six (1.12.0)
subprocess32 (3.2.7)
Theano (1.0.4)
wheel (0.30.0)

Do you know how to fix it?

Thanks.

**Comment by imadtyx** [comment]
One solution is that in [pg_su.py ](https://github.com/hongzimao/deeprm/blob/master/pg_su.py) file, in its 12th line, remove the parameter called `threshold= 'nan'`. 

But you won't be able to run that code since you can only suggest commits. So I suggest you fork this entire repo and then do the changes by yourself in your cloned repo.

**Comment by ArikRinberg** [comment]
I've removed the attribute and now getting the following error:
AttributeError: ('The following error happened while compiling the node', DeepCopyOp(b), '\n', "'module' object has no attribute '_get_ndarray_c_version'")

**Comment by ioannoa88** [comment]
I've downloaded the code locally to reproduce the experiments as well. When getting the raise ValueError("threshold must be numeric and non-NAN, try " error, simply replace the np.set_printoptions(threshold='nan') with the suggestion threshold=sys.maxsize. This will keep you going. Googling, you will find some posts justifying why. I hope that helps.
